title: Adventures in security and programming
author: Alex Yang
email: alexyang@tutanota.com
description: > # this means to ignore newlines until "show_exerpts:"
  A portfolio page for Alex Yang CTO of Secure Code LLC. Detailing out my
  projects and thoughts on programming, security, mobility.
show_excerpts: true # set to true to show excerpts on the homepage
baseurl:

defaults:
    scope:
      path: "assets/images"
    values:
      image: true

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  disquis_shortname: securecodellc
  style: black
  title: Alex Yang
  tagline: Code Specialist
  date_format: "%b %-d, %Y"
  style: black
  showNav: true
  showPicker: false

  # generate social links in footer
  social_links:
    twitter: securedev3
    github:  alexyang-pixel
    rss: rss

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
